### ISSUE TITLE
How you detect breaking changes?

### ISSUE THREAD

**Issue by mehdi-ra** [YunaBraska/git-info-action#4]
**What do you want to achieve?**
Hi :hand:
I want to know how you detect breaking changes. Analyzing the commit messages or files or ...?

**Comment by YunaBraska** [comment]
It is through conventional commits, so no black magic 🪄 

see https://www.conventionalcommits.org/en/v1.0.0/

**Comment by mehdi-ra** [comment]
I understand, but I would like to know if I squash every commit before merging a pull request!?

**Comment by YunaBraska** [comment]
There is no issue before squash as you have all commits in place.

when you Squash, then you change the git history and move every change into one single commit. So you would need to handle breaking changes indicators like ‘!’ by yourself. 

Let me know if you have another idea how to detect breaking changes after merge 🙃
